# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7131fb882fd058d8957aae1b6ac2bfd624b346feee0f399caf4a6d4c00affcc967e03aa889d04d2fe65df6cae632b5f1723e10c93e5feeb1a22f3cecbf1486

test:
  secret_key_base: ddd34eacf266358388dd7b5116bb7149c9e3a74298abd4d09011042f81d9f454f490afe6a7368321f9a090d96a7d95ca34bbc600c752fe41fa96ff613f69e089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
